# Lab 03 - Numpy Arrays

Complete the tasks listed below. You can submit the completed lab until 11:59 PM in the night.

### Task 1 (3 marks)

The __data__ folder contains five csv files with column names `Col_A`, `Col_B`, `Col_C`, `Col_D`, and `Col_E`, as well as some fictitious data. Write Python code that extracts all the lines from each file (except the first line which contains the columns names) and creates a list of those integers for each file. For example, the list of integers for the file `Y2015-data.csv` would be [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20].

Then write code that extracts the year (such as `Y2015`) from each file path (such as `data\\Y2015-data.csv`) and creates a key with that year in a dictionary named __data_dict__. The value for the key (e.g. `Y2015`) should be the list of integers extracted from that file (i.e. `Y2015-data.csv`). You can write all of the above mentioned code in a single cell.

Some starter code is reproduced below for your convenience. Also, the desired output __data_dict__ is shown below.

<img src="figs/data_dict.png" width="1200" height="200" align="left">

In [1]:
### Write your code below this comment.

In [4]:
import glob

In [5]:
path = 'data' # use your path
allFiles = []
allFiles = glob.glob(path + "/*.csv")

In [6]:
allFiles

['data\\Y2015-data.csv',
 'data\\Y2016-data.csv',
 'data\\Y2017-data.csv',
 'data\\Y2018-data.csv',
 'data\\Y2019-data.csv']

### Task 2 (0.5 mark)

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10 (inclusive of both ends).

In [8]:
### Write your code below this comment.
import numpy as np
# range2 - 11 = value from 2 - 10 and reshape to 3x3 metric
metrix33 =  np.arange(2, 11).reshape(3,3)
print(metrix33)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Task 3 (0.5 mark)

Write a NumPy program to convert the array __[1, 2, 3, 4, 5]__ to float type. Print both the original as well as the converted array.

In [10]:
### Write your code below this comment. 
arr = [1, 2, 3, 4,5 ]
print("Original array:")
print(arr)
#convert array to float array
farr = np.asfarray(arr)
print("Converted array:")
print(farr)

Original array:
[1, 2, 3, 4, 5]
Converted array:
[1. 2. 3. 4. 5.]


### Task 4 (2 marks)

Write a NumPy program to create a 5x5 matrix with all 1's. Then write code to modify the matrix such that it has 1 on the borders and 0 inside. Print both the original as well as the modified array. The following is a pictorial representation of such a matrix:

<img src="figs/array_border_1.png" width="200" height="200" align="left">

In [15]:
### Write your code below this comment.
import numpy as np
arr1 = np.ones((5,5))
print("Original array:")
print(arr1)

#row 1 to -1 and col 1 to -1 update to 0
print("1 on the border and 0 inside in the array")
arr1[1:-1,1:-1] = 0
print(arr1)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Task 5 (2 marks)

Write a NumPy program to get the unique elements of the arrays __[10, 10, 20, 20, 30, 30]__ and __[[1, 1], [2, 3]]__. Print both the original arrays as well as the arrays with unique elements. The following is a pictorial representation of this operation:

<img src="figs/array_unique.png" width="350" height="350" align="left">

In [17]:
### Write your code below this comment.
import numpy as np
a = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(a)

print("Unique elements of the above array:")
print(np.unique(a))

b = np.array([[1, 1], [2, 3]])
print("Original array:")
print(b)
print("Unique elements of the above array:")
print(np.unique(b))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


### Task 6 (2 marks)

Write a NumPy program to change the dimensions of the 1D array __[1, 2, 3, 4, 5, 6, 7, 8, 9]__ to a 3x3 matrix. Explain why the shape of the 1D array displays 9 rows and no columns although it has just a single row. How could this possibly be corrected?

In [30]:
### Write your code below this comment.
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1 Dimension array with 9 rows and 0 columns, actual answer is" , x.shape,  "matched with expectation with (9,)")

x.shape = (3, 3)
print("Convert 1 Dimension to 3 Dimensions")
print(x)

1 Dimension array with 9 rows and 0 columns, actual answer is (9,) matched with expectation with (9,)
Convert 1 Dimension to 3 Dimensions
[[1 2 3]
 [4 5 6]
 [7 8 9]]
